### ISSUE TITLE
'npm start' gives an error

### ISSUE THREAD

**Issue by ThedathUMCG** [uxpin-merge/uxpin-merge-boilerplate#24]
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
TypeError [ERR_INVALID_ARG_VALUE] [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 'E:\\02_programming\\uxpin\\uxpin-merge-boilerplate\\..srccomponentsButtonpresets\u0000-default.jsx\\package.json'
    at readFile (fs.js:317:10)
    at go$readFile (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\graceful-fs\graceful-fs.js:85:14)
    at Object.readFile (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\graceful-fs\graceful-fs.js:82:12)
    at Storage.provide (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:78:3)
    at CachedInputFileSystem.readFile (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:239:25)
    at CachedInputFileSystem._readJson (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:197:10)
    at Storage.provide (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:78:3)
    at CachedInputFileSystem.readJson (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:243:25)
    at E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:14:25
    at forEachBail (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\forEachBail.js:14:3)
    at findDescriptionFile (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:11:3)
    at Object.loadDescriptionFile (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:61:3)
    at E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:20:25
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Resolver.doResolve (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\Resolver.js:235:16)
    at E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\JoinRequestPlugin.js:21:13
    at _next41 (eval at create (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\tapable\lib\HookCodeFactory.js:33:10),
<anonymous>:6:1)
    at eval (eval at create (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:29:1)
    at E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:16:31
    at _next40 (eval at create (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\tapable\lib\HookCodeFactory.js:33:10),
<anonymous>:21:1)
    at eval (eval at create (E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:44:1)
    at E:\02_programming\uxpin\uxpin-merge-boilerplate\node_modules\enhanced-resolve\lib\AliasPlugin.js:53:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uxpin-merge-boilerplate@1.0.0 start: `uxpin-merge --webpack-config ./webpack.uxpin.config.js --wrapper ./src/components/UXPinWrapper/UXPinWrapper.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uxpin-merge-boilerplate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by matthewchigira** [comment]
Hi @ThedathUMCG, this issue is caused because of using Windows. In order to use Merge in a Windows environment, you will need to [follow these instructions](https://www.uxpin.com/docs/merge/working-on-windows) to install the WSL enviroment.
